# Generated by Django 4.0.2 on 2022-02-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hotspotregions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackerlocation',
            old_name='tracker_id',
            new_name='tracker',
        ),
    ]
