# Generated by Django 4.0.2 on 2022-02-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tracker_child_first_name_tracker_child_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerlocation',
            name='physical_address',
            field=models.CharField(default='na', max_length=255),
            preserve_default=False,
        ),
    ]
